name: "Gazpar 2 MQTT"
description: "Extracts GRDF data into MQTT a.o."
version: "0.3.0"
slug: "gazpar_2_mqtt"
init: false
homeassistant_api: true
host_network: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - addon_config:rw
  - homeassistant_config:rw  
  - all_addon_configs:rw
services:
  - mqtt:want  
options:
  verbose: true
schema:
  verbose: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?

