name: "Gazpar 2 MQTT"
description: "Extracts GRDF data into MQTT a.o."
version: "0.3.0"
slug: "gazpar_2_mqtt"
init: false
homeassistant_api: true
arch:
  - amd64
  - arm64
  - armv7
map:
  - addon_config:rw
  - homeassistant_config:rw  
options:
  verbose: true
  CONFIG_LOCATION: /config/gazpar_2_mqtt/config.yaml
schema:
  verbose: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
