name: "Gazpar 2 MQTT"
description: "Extracts GRDF data into MQTT a.o."
version: "0.3.0"
slug: "hello_world"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - addon_config:rw
  - homeassistant_config:rw  
options:
  log_level: info
  verbose: true
schema:
  GRDF_USERNAME: str
  GRDF_PASSWORD: str
  MQTT_HOST: str
  verbose: bool?
  mqttHost: str