name: "Gazpar 2 MQTT DEV"
description: "Extracts GRDF data into MQTT a.o."
version: 0.8.4.7
slug: "gazpar_2_mqtt_dev"
init: false
homeassistant_api: true
auth_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - addon_config:rw
  - addon_configs:rw
  - homeassistant_config:rw  
  - all_addon_configs:rw
services:
  - mqtt:need  
options:
  verbose: true
  mqtt_autodiscover: true
schema:
  verbose: bool?
  mqtt_autodiscover: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?

